cc_library(
    name = "Agent",
	hdrs = [
		"Agent.h",
	],
	srcs = [
		"Agent.cpp",
	],
	deps = [
		":Sandbox",
		"//third_party/python",
	],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "Sandbox",
	hdrs = [
		"Sandbox.h",
	],
	srcs = [
		"Sandbox.cpp",
	],
	deps = [
		"//third_party/python",
	],
)
