cc_library(
    name = "Windows",
	hdrs = ["WindowsWindow.h"],
    srcs = ["WindowsWindow.cpp"],
	deps = [
		"@glew//:glew",
		"@glfw//:glfw",
		"//src:tdrl",
		"//src/Events",
	],
    visibility = ["//visibility:public"],
)
